### PR TITLE
Add tests and small adjustments

### PR DESCRIPTION
**Pull request by mikezaschka**
While I've been working on a lot of stuff, that is now obsolete, here are a few more modifications:

- Substitute default placeholders with Postgres style ones ($1, $2...) and use the pg-libraries parameterized query
- Added some (20+) tests for the SQL builder and the OData service

### CODE REVIEW

**Comment by gregorwolf** [comment]
Hi @mikezaschka,
thank you for that great work. Maybe we find a way to either integrate my [pg-beershop](https://github.com/gregorwolf/pg-beershop) via a reference or can leave out the package.json and package-lock.json in the subfolder.
CU
Gregor

**Comment by mikezaschka** [comment]
I removed those inner package.json files and updated the gitignore so I can have them around locally.
I also started to add some data type specific stuff. It seems, there is still some work to do, because all the _advanced_ types tests (Date, DateTime, Decimal...) are currently failing.

**Comment by d-sooter** [comment]
There should be a post-processing method, maybe u can see if there is something missing there. Or is it just the test that is failing?

**Comment by mikezaschka** [comment]
> There should be a post-processing method, maybe u can see if there is something missing there. Or is it just the test that is failing?

The OData request is failing and thus the test. ;-) The request doesn't reach the conversion script. It's been blocked earlier by the odata-server. 
Are you able to send GET/POST requests with an Entity containing a Decimal property?

**Comment by gregorwolf** [comment]
Please increase the version in package.json to 0.0.7 so it will be published to npmjs when I merge.

**Comment by gregorwolf** [comment]
Please merge my PR to your repo and then lets merge here :-).

**Review by gregorwolf — APPROVED** [review]

**Pull request merged**
