### PR TITLE
Fix #358 case-insensitive filter

### LINKED ISSUE #358: Case-sensitive issue in filter operation
Hi,
We are facing case-sensitive issue while filter from ui5.
Suppose, a column value is stored as 'Flush'. If we filter from ui5 'Fl', then we get the data.
But if we write 'fl', we get no data.

Best regards.
Md. Ashraful Alam

### PR DESCRIPTION
**Pull request by ajewelbd**

### CODE REVIEW

**Comment by gregorwolf** [comment]
Please extend this pull request also with a unit test. A new test "case-insensitive" added to:

'__tests__/lib/pg/odata-string-functions.test.js'

would be perfect.

**Comment by ajewelbd** [comment]
@gregorwolf, Is anything extra needed.

Thanks.

**Comment by gregorwolf** [comment]
@vobu do you think additional tests are needed?

**Comment by vobu** [comment]
urp, sorry for not getting to this earlier :(
but +1 on the merge :)

**Pull request merged**
