### PR TITLE
feat: support SAP CP CF PG Hyperscaler Service

### PR DESCRIPTION
**Pull request by gregorwolf**

### CODE REVIEW

**Review by vobu — COMMENTED** [review]
so in the tests, you're treating the dockerized posgres as if it were a hyperscaler service?

**Comment by gregorwolf** [comment]
Yes, as a placeholder for test against a real connection.

**Comment by vobu** [comment]
👍
then i'd suggest to run the same suite of tests against the scp hyperscaler postgres as we do against the dockerized one. 
i'll look into that test re-use tomorrow.

**Review by gregorwolf — COMMENTED** [review]
LGTM

**Review by vobu — APPROVED** [review]

**Pull request merged**
