### PR TITLE
Fix #305 filter in expand

### LINKED ISSUE #305: $filter in an expand doesn't work
Hi.

I downloaded the pg-beershop project and I started to test some APIs, but then I could not filter an expanded entity.
I tried doing the following query and it throw this error:

http://localhost:4004/beershop/Beers?$count=true&$select=ID,abv,ibu,name&$expand=brewery($select=ID,name)&$filter=brewery/name eq 'asd'&$skip=0&$top=30

https://ibb.co/MBy9Kcd

And it throws this error in the console:

[cds] - error: missing FROM-clause entry for table "brewery"
    at Parser.parseErrorMessage (/home/alexandre/pg-beershop/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/alexandre/pg-beershop/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/alexandre/pg-beershop/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/alexandre/pg-beershop/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
  length: 118,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '73',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3541',
  routine: 'errorMissingRTE',
  id: '1541585',
  level: 'ERROR',
  timestamp: 1652712172856
}

Is this filter available right now or will it be implemented in the future?

Thanks

### PR DESCRIPTION
**Pull request by negativename**

### CODE REVIEW

**Comment by gregorwolf** [comment]
Hi @negativename,
thank you for your PR. Unfortunately the automated test is still failing. Is it working for you localy? What Node.JS Version do you use? What is your OS?

**Comment by negativename** [comment]
Hello!
Sorry for late reply, I didn't see the message. I think it was my fault, because I forgot to remove my wrong test from previous commit.

**Comment by gregorwolf** [comment]
Hi @negativename,

it would be great if you can also add a test to __tests__/lib/pg/service.test.js so we have also an example for the OData query translation.

**Comment by gregorwolf** [comment]
Also please rebase to the latest main.

**Comment by negativename** [comment]
Hi,
I found new cases with filtering by nested fields and in these cases my solution doesn't work. That's why I'm closing pull request.

**Comment by gregorwolf** [comment]
Hope you will provide a new PR.

**Pull request closed without merging**
