### PR TITLE
use snaky case for table name / view name

### PR DESCRIPTION
**Pull request by clockrun**
convert table and column name to snaky case

### CODE REVIEW

**Comment by clockrun** [comment]
perhaps we can use similar way like Spring.
https://www.baeldung.com/hibernate-field-naming-spring-boot

Predefine some naming strategy and let developer decide which one to use. In this case, we will need capire to support it.

**Comment by gregorwolf** [comment]
Hi @clockrun,

thank you for your suggestion. Have you tried running the tests localy before an after your changes? As you can see the tests are failing in CI.

KR, Gregor

**Comment by clockrun** [comment]
Hi Gregor,
Yes, that's something we need to discuss. SInce the naming convention has changed, all those unit test need to be rewrite. Let's confirm the design and then update test case.

Regards,
Clockrun

**Comment by vobu** [comment]
thanks for being onboard 🙏 - but `cds-pg` sailed has sailed into the official SAP harbor and become a bigger boat ⛵️😄 
https://github.com/cap-js/cds-dbs/tree/main/postgres
Please continue contributing there!

**Pull request closed without merging**
