### PR TITLE
issue 367 - Draft entity query error

### PR DESCRIPTION
**Pull request by ryegros**
Refers to https://github.com/sapmentors/cds-pg/issues/367 . Changes a query parser behaviour when dealing with entity without alias inside expression in "select" clause.

### CODE REVIEW

**Comment by gregorwolf** [comment]
Hi @ryegros,

thank you very much for your contribution. Could we use the existing, draft enabled Entity TypeChecksWithDraft instead of adding two new entities?

Best Regards
Gregor

**Comment by ryegros** [comment]
Hi @gregorwolf. 

Sorry for delay, I was quite busy since the begin of year and had no time to answer. 

I did some changes today to be less invasive on current data model test-cases.

Unfortunately, I was only able to reproduce the issue with two draft entities, so a created the TypeChecksSibling entity making reference to the existing entity TypeChecks (also needs to annotate TypeChecksWithDraft with '@cds.redirection.target' on service file).

It takes me some extra time because I had to deal with another error while making the changes, it seems that expand an entity that have virtual fields leads to another exception at:

[node_modules/@sap/cds/libx/_runtime/db/expand/expandCQNToJoin.js:677]
`
const cols = column.expand.filter(c => !c.expand && !(c.ref[0] in DRAFT_COLUMNS_MAP)).map(c => c.ref[0])
`
Seems like virtual fields don’t have a “ref” attribute, generating an exception.

But I think that this is a question for another issue, maybe at standard lib @sap/cds and also I’m not sure if it's a bug, feature or expected behavior. So, I used the "($select='field')" on expand odata query in the test case to avoid the virtual attribute.

Is there anything else that I can do to help, on this issue?

Best Regards
Rafael Yegros.

**Review by gregorwolf — APPROVED** [review]

**Comment by gregorwolf** [comment]
Thank you.

**Comment by ryegros** [comment]
Yes... sorry,  I removed the entity itself but forgot to remove the annotations references to the entity.

Glad to help.

**Pull request merged**
